### ISSUE TITLE
Import does not seem to work with relative path

### ISSUE THREAD

**Issue by stefanhenze** [christophercliff/metalsmith-less#12]
I have the plugin configured to match ```css/site.less```. In site.less, I import another file in the same folder with

    @import "colors";

It crashes with this error:

    { type: 'File',
	  message: '\'colors.less\' wasn\'t found',
	  filename: 'input',
	  index: 0,
	  line: 1,
	  callLine: NaN,
	  callExtract: undefined,
	  column: 0,
	  extract: [ undefined, '@import "colors";', '' ] }

The import work with 

    @import "/src/css/colors";

Is this a configuration problem somewhere on my end? I'd like to include Bootstrap less files but it would be rather tedious to have to change them all to use absolute paths.

**Comment by christophercliff** [comment]
The options get passed directly to LESS, so whatever you can do with LESS proper you can do with this plugin. I suspect your paths are not quite right. Take a look at this test: https://github.com/christophercliff/metalsmith-less/blob/master/test/index.js#L17-L30

And the source directory: https://github.com/christophercliff/metalsmith-less/tree/master/test/fixtures/import/src

**Comment by stefanhenze** [comment]
Thank you, that worked. My use of the plugin now looks like this:

	.use(less({
		pattern: 'css/site.less',
		parse: { paths: ['src/css'] }
	}))

I guess I assumed that LESS would look for files relative to where the file is that it's currently processing. And this is how it seems to me that other less parsers work. What's especially inelegant here is that the  pattern uses a different root (i.e. ```/src/```) than the parse path (i.e. ```/```).

Is it possible to pre-configure the parser to always include the current file's directory in the paths?

Either way, it would be super helpful if you could add the paths as an example to the main plugin documentation. I didn't know that this is where I would specify the path and it didn't even occur to me to search there.

**Comment by christophercliff** [comment]
I think it's best for a wrapper plugin to expose the underlying library as directly as possible. Otherwise you end up with different flavors of the same technology. This is a problem in the Grunt ecosystem, where you often need to re-learn the plugin API when you already know the library API.

I noticed they released LESS v2 recently, with a simpler API and better docs. Will update to make things clearer https://github.com/christophercliff/metalsmith-less/issues/13.

**Comment by stefanhenze** [comment]
Great, thank you!
