### ISSUE TITLE
2.0 fails to load

### ISSUE THREAD

**Issue by theqwertman** [christophercliff/metalsmith-less#15]
Using this metalsmith.json

```json
{
  "source": "src",
  "destination": "out",
  "plugins": {
    "metalsmith-less": true
  }
}
```

and the newest version of Metalsmith, running the metalsmith command yields to following error: `failed to require plugin "metalsmith-less".`

Downgrading to metalsmith-less@1.0.3 solves the problem.

**Comment by christophercliff** [comment]
What's happening is `metalsmith-less` is throwing because `true` is an invalid input. The Metalsmith executable swallows this exception and prints the above error.

This is maybe a bug. In the meantime, this should work:

```json
"metalsmith-less": {}
```

**Comment by theqwertman** [comment]
Thanks! That did work.
