### ISSUE TITLE
@import paths not relative to file

### ISSUE THREAD

**Issue by theqwertman** [christophercliff/metalsmith-less#16]
Given this folder structure,
```
src/
    style.less
    includes/
        style-utilities.less
```

, and this style.less,
```less
@import 'includes/style-utilities';
```

, my @import statements fail unless I precede them with 'src/'. It appears, then, as if the includes are being treated as relative to the executable rather than the less file. This is inconvenient since most IDEs expect the @import path to be relative to its less file.

**Comment by christophercliff** [comment]
The plugin exposes the LESS API directly, so anything you can do with LESS you can do here. See tests for an example of what you want to do: https://github.com/christophercliff/metalsmith-less/blob/0c858b41a4eec3a30785434c30b9b08458130ff0/test/index.js#L17-L32.

**Comment by theqwertman** [comment]
It seems to me that the __default__ behavior of metalsmith-less should be to allow for relative includes.

Could you re-open this issue? I don't see how your linked example has anything to do with specifying less' working directory or enabling relative includes. I'll continue to look for the answer myself, but until a clear solution is provided here, it would be nice to have this marked as open so that others may chime in.
