### ISSUE TITLE
Delete LESS files after processing

### ISSUE THREAD

**Issue by harbichidian** [christophercliff/metalsmith-less#17]
As is, `metalsmith-less` doesn't remove the LESS files after processing, which results in a CSS _and_ a LESS file in the destination directory. I'd prefer an option to remove the LESS files, so only the CSS files get sent to the destination.

**Comment by BlueHayes** [comment]
:+1:

**Comment by christophercliff** [comment]
I'll leave this open for now, but recommend you make use of https://github.com/segmentio/metalsmith-ignore to clean up your build directory.

**Comment by christophercliff** [comment]
[`#ignore(path)`](https://github.com/segmentio/metalsmith#ignorepath) is now part of the core API.

**Comment by tschaub** [comment]
Can you add a bit more detail on how you suggest that `ignore` be used?

If I do the following, then my `less` files don't get passed to this plugin:
```
Metalsmith('.')
  .src('src')
  .dest('dest')
  .use(less())
  .ignore('**/*.less')
  .build(function(err) {
    if (err) {
      throw err;
    }
  });
```

As mentioned here https://github.com/segmentio/metalsmith/issues/145#issuecomment-120660748, I also would have assumed that plugins that transform file remove the input files.

**Comment by christophercliff** [comment]
Oh, I didn't realize `ignore` worked that way. I use https://github.com/segmentio/metalsmith-ignore, run last to clean up anything I don't want in the build directory.

**Comment by jhyland87** [comment]
This helped me as well! Thanks @tschaub
