### ISSUE TITLE
Trouble parsing the right files

### ISSUE THREAD

**Issue by BlueHayes** [christophercliff/metalsmith-less#18]
Ok so I've tried:

```js
Metalsmith(__dirname)
  .use(less({
    pattern: 'less/main.less'
  }))
```

In this case, imports in main.less cannot be found.

I've also tried:

```js
Metalsmith(__dirname)
  .use(less({
    pattern: 'less/**/*.less'
  }))
```

In this case, all less files are processed individually which results in an error because mixins can't be found for some files.

Any ideas?

Thanks

**Comment by christophercliff** [comment]
See test case using LESS's `paths` option: https://github.com/christophercliff/metalsmith-less/blob/0c858b41a4eec3a30785434c30b9b08458130ff0/test/index.js#L22-L24
