### ISSUE TITLE
Make it possible to load LESS files outside the src directory

### ISSUE THREAD

**Issue by alexzaporozhets** [christophercliff/metalsmith-less#20]
Hi, we are trying implement a separate folder for theme (templates, JS, LESS).

![package_json_-_website-metalsmith_-____webstormprojects_website-metalsmith_](https://cloud.githubusercontent.com/assets/891472/9056463/ce165ab8-3a9b-11e5-9922-2517cd84eca4.png)

The trouble is your plugin is not able to read the files outside the src folder.

**Comment by christophercliff** [comment]
Metalsmith only loads from the source directory. You may be able to load a file from source and use LESS to `@import` from other directories, see https://github.com/christophercliff/metalsmith-less/issues/19#issuecomment-122474451.
