### ISSUE TITLE
wrong cwd for includes

### ISSUE THREAD

**Issue by tcurdt** [christophercliff/metalsmith-less#21]
Two less files in the very same directory has

    @import "sub.less";

yet it fails to import. Presumably because of the wrong cwd.
Not sure if there is a way to pass that into less.

So this could be an issue of `less` itself - but this certainly is a blocker.

**Comment by christophercliff** [comment]
See:

- https://github.com/christophercliff/metalsmith-less/issues/19#issuecomment-122474451
- https://github.com/christophercliff/metalsmith-less/blob/0c858b41a4eec3a30785434c30b9b08458130ff0/test/index.js#L19-L26
- https://github.com/christophercliff/metalsmith-less/issues/22
