### ISSUE TITLE
include min in filename for minified css

### ISSUE THREAD

**Issue by oupala** [christophercliff/metalsmith-less#23]
I'm using metalsmith-less to render less files and concatenate them in one file:

```js
    .use(less({
        pattern: ['less/app.less'],
        render: {
            paths: [ // specify search paths for @import directives
                'src/less/',
                'src/less/bootstrap/',
                'src/less/components/'
            ],
            ieCompat: false, // see https://www.npmjs.org/package/grunt-contrib-less
            compress: true // minify css output
        },
        useDynamicSourceMap: true
    }))
```

It appears that the destination filename is generated from the source filename: `app.less` becomes `app.css`.

As the css has been minified, I would like the destination file to be names as `app.min.css`. It would meaningless to name the source file `app.min.less`.

It should be the role of metalsmith-less that rename the file to `file.min.css` if it has been compressed (minified).

**Comment by christophercliff** [comment]
I don't think this should be the responsibility of this plugin. More appropriate as a separate plugin or a wrapper.
